#! /bin/csh -vf

rm *dat

foreach SUFFIX  ( 1 2 3 4 5 ) 

   echo "This is a test." > file${SUFFIX}.dat
   echo "This is the second line." >> file${SUFFIX}.dat
   
   awk '{ print $3, $4, $1 }' file${SUFFIX}.dat > file_awked${SUFFIX}.dat
   
   
end 

