## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file SagemathGraphExample.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_40 = Integer(40); _sage_const_41 = Integer(41); _sage_const_47 = Integer(47); _sage_const_34 = Integer(34); _sage_const_3p5 = RealNumber('3.5'); _sage_const_2p1 = RealNumber('2.1'); _sage_const_39 = Integer(39); _sage_const_55 = Integer(55); _sage_const_54 = Integer(54); _sage_const_53 = Integer(53); _sage_const_52 = Integer(52); _sage_const_51 = Integer(51)## This file (SagemathGraphExample.sagetex.sage) was *autogenerated* from SagemathGraphExample.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('SagemathGraphExample', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_34 
_st_.blockbegin()
try:
 H= graphs.PetersenGraph()
 H.set_latex_options(scale=_sage_const_3p5 ,graphic_size=(_sage_const_2p1 ,_sage_const_2p1 ))
 Chi = H.chromatic_number(algorithm="DLX")
 Beta = H.independent_set()
except:
 _st_.goboom(_sage_const_39 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_40 
 _st_.inline(_sage_const_0 , latex(H.order()))
except:
 _st_.goboom(_sage_const_40 )
try:
 _st_.current_tex_line = _sage_const_41 
 _st_.inline(_sage_const_1 , latex(H.size()))
except:
 _st_.goboom(_sage_const_41 )
try:
 _st_.current_tex_line = _sage_const_47 
 _st_.inline(_sage_const_2 , latex(H))
except:
 _st_.goboom(_sage_const_47 )
try:
 _st_.current_tex_line = _sage_const_51 
 _st_.inline(_sage_const_3 , latex(Chi))
except:
 _st_.goboom(_sage_const_51 )
try:
 _st_.current_tex_line = _sage_const_52 
 _st_.inline(_sage_const_4 , latex(len(Beta)))
except:
 _st_.goboom(_sage_const_52 )
try:
 _st_.current_tex_line = _sage_const_52 
 _st_.inline(_sage_const_5 , latex(Beta))
except:
 _st_.goboom(_sage_const_52 )
try:
 _st_.current_tex_line = _sage_const_53 
 _st_.inline(_sage_const_6 , latex(H.clique_number()))
except:
 _st_.goboom(_sage_const_53 )
try:
 _st_.current_tex_line = _sage_const_54 
 _st_.inline(_sage_const_7 , latex(H.clique_maximum()))
except:
 _st_.goboom(_sage_const_54 )
try:
 _st_.current_tex_line = _sage_const_54 
 _st_.inline(_sage_const_8 , latex(H.diameter()))
except:
 _st_.goboom(_sage_const_54 )
try:
 _st_.current_tex_line = _sage_const_55 
 _st_.inline(_sage_const_9 , latex(H.radius()))
except:
 _st_.goboom(_sage_const_55 )
_st_.endofdoc()

