#! /bin/csh -f

# Link biblio files to masters in ~/BibTex
ln -sf ~/LatexBib/math.bib math.bib
ln -sf ~/LatexBib/ca.bib ca.bib
ln -sf ~/LatexBib/smith.bib smith.bib
ln -sf ~/LatexBib/thal.bib thal.bib
ln -sf ~/LatexBib/edu.bib edu.bib
ln -sf ~/LatexBib/jneurophys.bst jneurophys.bst 
ln -sf ~/LatexDef/ca_def.tex  ca_def.tex
ln -sf ~/LatexDef/math_def.tex  math_def.tex
ln -sf ~/LatexDef/common_def.tex  common_def.tex

