#!/usr/bin/env python3
# Build a multipage review PDF from PDFs inside directories matching Fig*.
# Each input PDF contributes one page to the output. The PDF is scaled to fit on
# a landscape letter page, and the relative PDF filename is printed directly
# beneath it on the same page.
# By default this writes fig_pdf_review.tex, compiles fig_pdf_review.pdf,
# and opens the result for inspection.

from __future__ import annotations

import argparse
import glob
from pathlib import Path
import re
import subprocess
import sys


DEFAULT_OUTPUT = Path("fig_pdf_review.pdf")


def natural_key(path: Path) -> list[object]:
    return [
        int(part) if part.isdigit() else part.lower()
        for part in re.split(r"(\d+)", path.as_posix())
    ]


def unique_sorted(paths: list[Path]) -> list[Path]:
    seen: dict[Path, Path] = {}
    for path in paths:
        resolved = path.resolve()
        if resolved not in seen:
            seen[resolved] = path
    return sorted(seen.values(), key=natural_key)


def collect_pdfs(targets: list[str], recursive: bool) -> list[Path]:
    pdfs: list[Path] = []
    for target in targets:
        matches = [Path(match) for match in glob.glob(target)] or [Path(target)]
        for match in matches:
            if match.is_dir():
                pattern = "**/*.pdf" if recursive else "*.pdf"
                pdfs.extend(match.glob(pattern))
            elif match.is_file() and match.suffix.lower() == ".pdf":
                pdfs.append(match)
    return unique_sorted(pdfs)


def tex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def latex_include_path(path: Path) -> str:
    return path.as_posix().replace("\\", "/")


def build_tex(pdfs: list[Path]) -> str:
    lines = [
        "% Generated by make_fig_pdf_review.py.\n",
        "\\documentclass[11pt,landscape]{article}\n",
        "\\usepackage[paper=letterpaper,margin=0.35in]{geometry}\n",
        "\\usepackage{graphicx}\n",
        "\\pagestyle{empty}\n",
        "\\setlength{\\parindent}{0pt}\n",
        "\n",
        "\\newcommand{\\reviewpage}[2]{%\n",
        "    \\begin{minipage}[c][\\textheight][c]{\\textwidth}\n",
        "        \\centering\n",
        "        \\includegraphics[\n",
        "            page=1,\n",
        "            width=0.96\\textwidth,\n",
        "            height=0.82\\textheight,\n",
        "            keepaspectratio\n",
        "        ]{#1}\\\\[0.16in]\n",
        "        {\\ttfamily\\small #2}\n",
        "    \\end{minipage}\n",
        "    \\clearpage\n",
        "}\n",
        "\n",
        "\\begin{document}\n",
    ]

    for pdf in pdfs:
        include_path = latex_include_path(pdf)
        label = tex_escape(pdf.as_posix())
        lines.extend(
            [
                "\n",
                f"\\reviewpage{{{include_path}}}{{{label}}}\n",
            ]
        )

    lines.append("\n\\end{document}\n")
    return "".join(lines)


def compile_tex(tex_path: Path, pdflatex: str) -> bool:
    command = [
        pdflatex,
        "-interaction=nonstopmode",
        "-halt-on-error",
        tex_path.name,
    ]
    result = subprocess.run(
        command,
        cwd=tex_path.parent or Path("."),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        print(f"{tex_path}: pdflatex failed", file=sys.stderr)
        print("\n".join(result.stdout.splitlines()[-40:]), file=sys.stderr)
        return False

    for suffix in (".aux", ".log", ".out"):
        path = tex_path.with_suffix(suffix)
        if path.exists():
            path.unlink()
    return True


def open_pdf(pdf_path: Path) -> None:
    def try_open(command: list[str]) -> bool:
        result = subprocess.run(
            command,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        return result.returncode == 0

    if sys.platform == "darwin":
        if try_open(["open", str(pdf_path)]):
            return
        if try_open(["open", "-b", "com.apple.Preview", str(pdf_path)]):
            return
        try_open(["open", "-a", "/System/Applications/Preview.app", str(pdf_path)])
        return

    try_open(["xdg-open", str(pdf_path)])


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Create a labeled multipage PDF from PDFs in Fig* directories."
    )
    parser.add_argument(
        "targets",
        nargs="*",
        default=["Fig*"],
        help="Directories, PDF files, or glob patterns. Default: Fig*",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output PDF path. Default: {DEFAULT_OUTPUT}",
    )
    parser.add_argument(
        "--tex",
        type=Path,
        help="Generated .tex path. Default: output PDF path with .tex suffix.",
    )
    parser.add_argument(
        "--recursive",
        action="store_true",
        help="Find PDFs recursively below matched directories.",
    )
    parser.add_argument(
        "--tex-only",
        action="store_true",
        help="Write the .tex file without compiling.",
    )
    parser.add_argument(
        "--no-open",
        action="store_true",
        help="Do not open the generated PDF after compiling.",
    )
    parser.add_argument(
        "--pdflatex",
        default="pdflatex",
        help="pdflatex executable to use.",
    )
    args = parser.parse_args()

    output_pdf = args.output
    tex_path = args.tex or output_pdf.with_suffix(".tex")
    pdfs = collect_pdfs(args.targets, recursive=args.recursive)
    if not pdfs:
        print("No matching PDFs found.", file=sys.stderr)
        return 1

    tex_path.write_text(build_tex(pdfs), encoding="utf-8")
    print(f"Wrote {tex_path} with {len(pdfs)} included PDFs.")

    if args.tex_only:
        return 0

    if not compile_tex(tex_path, args.pdflatex):
        return 1

    compiled_pdf = tex_path.with_suffix(".pdf")
    if compiled_pdf != output_pdf:
        compiled_pdf.replace(output_pdf)

    print(f"Wrote {output_pdf}.")
    if not args.no_open:
        open_pdf(output_pdf)
    return 0


if __name__ == "__main__":
    sys.exit(main())
